nickel_macros/src/macro.rs
src/lib.rs
src/middleware_handler.rs
src/mimes.rs

Fix router macro (use {} instead of ())

---

Cargo.toml
README.md
examples/example.rs
examples/example_route_data.rs
examples/example_template.rs
examples/example_with_default_router.rs
examples/hello_world.rs
examples/macro_example.rs
nickel_macros/src/macro.rs
src/default_error_handler.rs
src/favicon_handler.rs
src/json_body_parser.rs
src/lib.rs
src/middleware.rs
src/middleware_handler.rs
src/mimes.rs
src/nickel.rs
src/nickel_error.rs
src/query_string.rs
src/request.rs
src/response.rs
src/router/http_router.rs
src/router/mod.rs
src/router/router.rs
src/server.rs
src/static_files_handler.rs

[WIP] Make it build with Rust 1.0.0-alpha

---

src/mimes.rs
src/nickel_error.rs

fix(*): Show is deprecated in favor of Debug

---

examples/example.rs
src/mimes.rs
src/response.rs

fix(*): FromStr now returns a Result, not an Option.

---

src/lib.rs
src/response.rs
src/static_files_handler.rs

fix(*): std::path is now std::old_path

---

src/json_body_parser.rs
src/query_string.rs

Updates to rust-plugin broke our code. This fixes it.

Update to work with latest rust-plugin

---

examples/hello_world.rs
examples/macro_example.rs
src/lib.rs
src/router/http_router.rs

Fixes the build on travis, it was failing from missing parenthesis (seemed like that was a buggy compile or something, couldnt reproduce locally).

fix(plugin): update plugin syntax

---

examples/example_route_data.rs
src/lib.rs

Fixes for nightly

---

examples/example.rs
examples/macro_example.rs
src/favicon_handler.rs
src/json_body_parser.rs
src/lib.rs
src/nickel_error.rs
src/query_string.rs
src/response.rs
src/router/mod.rs
src/router/router.rs
src/static_files_handler.rs

This depends on https://github.com/reem/rust-typemap/pull/22 and https://github.com/sfackler/rust-openssl/pull/166 being pulled and published.

fix(*): fix depreciated code

---

Cargo.toml
src/middleware_handler.rs
src/router/router.rs

Embarrassing cause of one of the problems in #162

fix(mime): set Content-Type header when appropriate

---

src/lib.rs

chore(*): remove build warnings

---

README.md
examples/example.rs
examples/macro_example.rs
nickel_macros/src/macro.rs
src/favicon_handler.rs
src/lib.rs
src/query_string.rs
src/router/router.rs
src/static_files_handler.rs
src/urlencoded.rs

Waiting on unsafe-any and typemap to get new versions published, so this will fail travis until later.

fix(rustup): forced feature gates and generic conversions landed

---

Cargo.toml
examples/macro_example.rs
src/json_body_parser.rs
src/lib.rs
src/middleware_handler.rs
src/mimes.rs
src/nickel_error.rs
src/response.rs
src/server.rs
src/static_files_handler.rs

Also now using groupable from `crates.io`

fix(rustup): Coherence and Error changes

---

Cargo.toml
README.md
examples/example.rs
examples/macro_example.rs
src/lib.rs
src/nickel.rs
src/router/http_router.rs
src/router/into_matcher.rs
src/router/matcher.rs
src/router/mod.rs
src/router/router.rs

This is based on top of #170 so will need rebasing for any changes there, alternatively I can rebase on master if that gets rejected. 
The last 3 commits are the ones worth looking at.
Closes #101.

Regex routes

---

src/json_body_parser.rs

rust-lang/rust#23979 has landed, so we can have nice JSON error messages!

Improve the error message on failure to parse JSON

---

.travis.yml
Cargo.toml
README.md
src/middleware_handler.rs

Fix custom error handlers not being called

---

src/router/http_router.rs

feat(router): add convenience methods for OPTIONS and PATCH

---

src/router/router.rs

@lambdaburrito raised a PR here (https://github.com/nickel-org/nickel.rs/pull/190) but I think he may be MIA now. It's only a minor change so I did the tidy up for him/her. 
I also renamed the variables from ```regex1``` etc and made them a bit more descriptive

lambdaburrito's PR tidied up

---

.travis.yml

Hopefully got it setup correctly!

Publish docs on build

---

Cargo.toml
examples/moved_ownership.rs
src/responder.rs

@cburgdorf This is related to the issue you mentioned on gitter

fix(responder): relax required lifetime for responding with string slices

---

.travis.yml

chore(travis): Build on latest stable rust.

---

src/lib.rs
src/nickel.rs
src/nickel_error.rs
src/response.rs
src/router/http_router.rs

Minor cleanup

---

src/response.rs

Relates to #257
@Ryman @SimonPersson

feat(render): improve ergonomics of send_file

---

Cargo.toml
examples/chaining.rs
src/nickel.rs
src/router/http_router.rs
src/router/router.rs

feat(router): add chainable routes

---

Cargo.toml
examples/form_data/form_data.rs
examples/form_data/views/confirmation.html
examples/form_data/views/contact.html

<h2>Complete example handling form data</h2>
In regards to ticket number <a href="https://github.com/nickel-org/nickel.rs/issues/240#issuecomment-127655614">#240</a>
If you would like me to strip the cargo package before upload and just leave the "views" and "main.rs" just let me know. 
All that needs to be added now is the url parse.

Example handling form data

---

src/request.rs
src/response.rs

fix(serverdata): extend lifetime of return value of {Request|Response}::server_data

---

Cargo.toml
examples/example.rs
examples/hello_world.rs
examples/hello_world_macro.rs
src/middleware.rs

doc(examples): add examples without macro usage

---

src/extensions/mod.rs
src/extensions/request.rs
src/extensions/response.rs
src/lib.rs

Improve ergonomics of redirects

---

Cargo.toml
changelog.md

Remove wildcard dependencies

---

src/lib.rs
src/nickel.rs

The original PR (#277) appears to be dead. @ixjf

feat(nickel): add options to Nickel, redux

---

Cargo.toml
examples/enable_cors.rs
tests/example_tests.rs
tests/examples/enable_cors.rs

doc(examples): add an example enabling cors

---

src/nickel.rs
src/server.rs

Add an option for server thread count from #309 to the new Options API.

feat(options): add an option for thread count

---

Cargo.toml
examples/no_macro_custom_data.rs

Related to my question [here](https://github.com/nickel-org/nickel.rs/issues/351).

doc(examples): add an example for using server data (without macros)

---

README.md

Recreating pull request #397 with the standard commit format.

doc(Readme): Fix little typos

---

src/lib.rs

fix(*): publically export hyper

---

Cargo.toml
examples/integration_testing.rs
examples/json.rs
examples/macro_example.rs
src/body_parser.rs
src/lib.rs
src/responder.rs
src/response.rs
src/template_cache.rs
tests/example_tests.rs
tests/examples/json.rs

feat(serde): replace rustc_serialize with serde
