examples/example.rs
examples/example_route_data.rs
examples/example_template.rs
examples/example_with_default_router.rs
examples/hello_world.rs
examples/macro_example.rs
src/favicon_handler.rs
src/nickel.rs
src/response.rs
src/server.rs
src/static_files_handler.rs

The `io` module was renamed `old_io` and deprecated. As far as I can see, there's no new `io` module yet so we'll have to use `old_io` until the new `io` module arrives.

fix(*): IO module was renamed.

---

src/middleware_handler.rs

fix(middleware_handler): use from_usize instead of from_uint

---

src/static_files_handler.rs

A follow-up feature would be to support directory
listings from StaticFilesHandler.

fix(StaticFilesHandler): don't try to send dirs

---

README.md
examples/example.rs
examples/example_route_data.rs
examples/example_template.rs
examples/example_with_default_router.rs
examples/hello_world.rs
examples/macro_example.rs
src/as_bytes.rs
src/default_error_handler.rs
src/favicon_handler.rs
src/json_body_parser.rs
src/lib.rs
src/middleware.rs
src/middleware_handler.rs
src/nickel.rs
src/nickel_error.rs
src/query_string.rs
src/request.rs
src/response.rs
src/router/router.rs
src/server.rs
src/static_files_handler.rs

Alternative to #168. 
Providing a separate PR incase the design isn't agreeable (this is based on that branch). 
These changes make it easier to enforce standard behavior. HTTP doesn't really allow changing the status code once a response is already in progress, so users should either bail (and log) or start an error with an appropriate code which error handlers can process. 
I considered changing the API for an ErrorHandler to take `&mut Option<Response<Streaming>>` but decided to keep `NickelError` as in the absense of a `Response` we can at least still know what the developers error message was (in case they want to log *something* to a database rather than *nothing*).

Refactor Response API and trim NickelError

---

src/lib.rs
src/middleware_handler.rs
src/response.rs

cc #162, @SimonPersson, @ninjabear 
The 2nd commit is really just a temporary fix, we will need to adjust the `Response` api to deal with a different error type rather than `io::Result` otherwise things like this won't propagate to error handlers and it will be easy to drop the Response without flushing the buffer (which is causing the deadlocks). Hopefully deadlocks die off (no pun intended) once the 'new io' has support for timeouts, but for now we're going to have to develop an api that can hopefully ensure that it is impossible to lose the `Response` in a handler without a panic.

Default Content-Type & Temp fix for send_file deadlocking on non-existant files

---

examples/example_route_data.rs
src/macros.rs
src/middleware_handler.rs
src/router/http_router.rs
src/router/router.rs

This is a bit of a compromise, allowing unboxed closures to be used for handlers but not for `Middleware`, while also making the routing a bit less flexible for the moment (can only take unboxed closures and not a `Middleware`, so you can't have a `Router` dispatch to another `Middleware` without wrapping a closure).
The second commit shows an alternative that I encountered while refactoring. If we deem macros acceptable in the time being we could follow that approach, as we maintain flexibility with only a minor syntactic wart. I favor this approach, but wanted to show how the example usage could look without any macros, which is the current state of the PR. Whenever https://github.com/rust-lang/rust/issues/24680 is fixed, we should then be able to depreciate the macro and the user code …

feat(unboxed_closures): allow unboxed closures for handlers and error handlers

---

examples/example.rs
src/macros.rs

If they can't bind response mutably, they can't call &mut methods on the Response and set headers. Otherwise, to use `response.content_type()`, middleware creators must create a function instead of using the middleware! macro.

Allow middleware to bind response mutably

---

src/json_body_parser.rs

This is unnecessary as we don't really need ownership of the Body
to parse the Json.
[breaking-change]

refactor(json): remove unnecessary Rc usage

---

examples/example.rs
examples/macro_example.rs
src/lib.rs
src/query_string.rs
src/router/router.rs

I'd like to bikeshed on this API a bit.
Due to requiring a mutable reference to update the cached value, we can't return a view from `query`. This changes it to return a `store` which then you can then query into as much as you want without borrowck problems. An alternative is to keep the current api and then have a second method which returns the store like this currently does and maintaining the old api for the simple/average case.
I'm actually more in favor of changing the API a bit further, as I think most users will be wanting the first value in the set of matches so we should make that nicer.
```rust
let q : Query = req.query();
let bar : Option<&str> = q["bar"];
let bar : &str = bar.unwrap_or("default");
// When it only needs to live for the call
let bar : Option<&str> = …
```

fix(query): allow multiple query params alive at once

---

README.md
contributing.md

#159 was the original source of this, but I remembered finding it quite hard to understand the readme before because it contains a lot of information on various aspects of nickel development, imo all it really needs to have is a status, how to helloworld and where to find out more. 
I appreciate the readme is pretty subjective and am not suggesting this PR be accepted entirely as is - I'm open to changing it up

Reword the readme and split contributor information into another file

---

src/request.rs
src/router/router.rs
src/static_files_handler.rs
tests/compile-fail/inference_request_hinted.rs

fix(static_files): ignore the querystring during static file lookup

---

examples/example.rs
examples/example_with_default_router.rs
examples/macro_example.rs
src/request.rs
src/router/http_router.rs
src/router/router.rs

A user may wish to use the same handler for multiple routes,
if the behaviour of such a handler should differ based on the
available params then the handler it will panic at runtime as
there is no convenient way to check for the presence of the
param before accessing it.
For broken code:
If you have `foo.param("bar")` then you'll need to `unwrap` the
Option, e.g. `foo.param("bar").unwrap()`.
[breaking-change]

fix(request): request.param(_) now returns an Option

---

.travis.yml
contributing.md

hyper is tracking stable, so to keep things simple as rust develops, we should focus on the stable release channel as our moving target.
@cburgdorf @SimonPersson any hesitation?

Remove 1.0 build target from travis

---

Cargo.toml

I'm sorry for the mess earlier. Everything has been cleaned up now.
In order for Windows users to be able to use nickel without having to install MinGW and OpenSSL, I'm making Hyper's SSL feature optional. It can be disabled by adding 'default-features = false' in your [dependencies.nickel]. This is related to the issue #274 that I reported yesterday.

feat(ssl): make Hyper's SSL feature optional

---

.travis.yml

This was overlooked when we removed the 1.0.0 build target

fix(travis): resume publishing docs

---

examples/macro_example.rs
src/default_error_handler.rs
src/favicon_handler.rs
src/json_body_parser.rs
src/macros/middleware.rs
src/middleware.rs
src/mount.rs
src/nickel.rs
src/nickel_error.rs
src/query_string.rs
src/request.rs
src/responder.rs
src/response.rs
src/router/http_router.rs
src/router/router.rs
src/server.rs
src/static_files_handler.rs
tests/compile-fail/inference_fully_hinted.rs
tests/compile-fail/inference_no_hints.rs
tests/compile-fail/inference_request_hinted.rs
tests/compile-fail/inference_response_hinted.rs

I've ripped out the core from #272 and decided we should just push separate crates for now until the implementation for Session/Cookies has settled. This allows more breaking changes to the session/cookies implementations as we experiment without requiring a load of version bumps to nickel itself. It's more work for us to manage, but should be better for users :+1: 
I've also added a default type for the typeparam, so breakage in client crates should be minimal (until they start using the dataparam!) and only really affect people who've written library level stuff.
r? @cburgdorf @SimonPersson

feat(server): shared data between requests and plugins for Response

---

src/macros/middleware.rs

This can sometimes be required when using some middleware which are
predicated on the datatype of the Server. An alternative would be to
litter the handler with extra type annotations (which is awkward without
type ascription), or to use explicit type-annotated functions as middleware.
Example usage:
```
middleware! { |res| <ServerData>
// res is of type Response<ServerData>
}
```

feat(macros): allow hinting the server data type in middleware macro

---

.clog.toml
Cargo.toml
changelog.md

Manually added the references to breaking changes, due to https://github.com/clog-tool/clog-cli/issues/76.

chore(*): release 0.7.0

---

src/response.rs

fix(send_file): don't overwrite the ContentType header if it exists

---

examples/macro_example.rs
src/favicon_handler.rs
src/middleware.rs
src/responder.rs
src/response.rs
src/router/router.rs
src/static_files_handler.rs

This seems more intuitive, less imports, less types to know about, does what it says.

feat(response): add next_middleware method for convenience

---

.travis.yml
Cargo.toml
src/nickel.rs
src/server.rs

This was disabled in hyper 0.6.15 which gave a significant performance regression. 
In the same release though `socket_timeouts` related code was included which allows us to add timeouts on the socket which should prevent threads being stalled indefinitely. With the `timeouts` features enabled this should match 0.6.14 performance and not lead to exhausted servers (although it can still happen, but they will recover, unlike before).
When the `timeouts` feature is disabled (to compile on 1.3), the performance should match the previous, but the keep-alive issues that were previously present will still occur, so it's probably best for users of 1.3 to either upgrade or to set `keep_alive_timeout` to `None`. 
I'm unsure if we should continue to support 1.3 with such a limitation. (especially …

perf(hyper): re-enable keep-alive by default

---

examples/template.rs

Seems the crate is [written with an underscore](https://crates.io/crates/nickel_mustache)

doc(examples): Point to correct crate

---

.travis.yml

Rust 1.7 is new minimum due to url bumping to new uuid version (which added no_std support) and cookie bumping to url 1.0 which depends on IpAddr which was destabilized in 1.6 and then restabilized in 1.7.

chore(travis): bump minimum rust version

---

.travis.yml
tests/compile-fail/inference_no_hints.rs
tests/compile-fail/inference_request_hinted.rs

This still keeps the minimum rustc version tested on travis as a canary for when things do inevitably fail in future.

fix(travis): Don't fail the build when minimum rustc version fails

---

src/mimes.rs

By moving common code out of the match arms, compile times for
optimized builds are reduced by about 25% on my box, and the resulting
binary is almost 500kb smaller.

chore(mimes): improve macro definitions

---

Cargo.toml
examples/chaining.rs
examples/custom_error_handler.rs
examples/enable_cors.rs
examples/form_data/form_data.rs
examples/hello_world.rs
examples/hello_world_macro.rs
examples/https.rs
examples/integration_testing.rs
examples/json.rs
examples/logger_middleware.rs
examples/macro_example.rs
examples/mount.rs
examples/moved_ownership.rs
examples/query_string.rs
examples/regex_route.rs
examples/route_data.rs
examples/routing.rs
examples/static_files.rs
examples/template.rs
src/lib.rs
src/macros/middleware.rs
src/nickel.rs
src/server.rs
tests/compile-fail/inference_fully_hinted.rs
tests/compile-fail/inference_no_hints.rs
tests/compile-fail/inference_request_hinted.rs
tests/compile-fail/inference_response_hinted.rs
tests/example_tests.rs
tests/examples/integration_testing.rs

Related to #328.
The tests within this repo are a bit of a hack (require shelling out to subprocesses involving cargo), with this change we can instead make it *easier* to integration test a server (or multiple instances of one) all within the same process which should be easier and faster.
The code within the integration test example would get tested using a normal `cargo test`, but since it's in our example files I had to use a workaround to get it compiled directly into our integration test runner.
BREAKING CHANGE: This changes the return type of `Nickel::listen`, you can add an `unwrap()` to the call to maintain previous semantics.

feat(server): return `ListeningServer` from `Nickel::listen`

---

Cargo.toml
src/nickel.rs
src/server.rs
src/urlencoded.rs

Also move listen_https to be unconditionally included since openssl
isn't required by hyper anymore.
This is a rebase of #341 with some minor changes.

chore(*): Upgrade hyper and url versions

---

src/response.rs

It looks like the Authorization<Bearer> type [just didn't exist](https://github.com/hyperium/hyper/commit/edf6ac2074d11694ded275807a66df3a8a8e33a6#diff-1af6105c3e0313f3d4e68615037d890b)
at the time the `set` method and `Modifiers` [were created](https://github.com/nickel-org/nickel.rs/commit/182517b89a232a715b2fde82efbe507cef96037e#diff-6cfc163228cc31bed4a7214fa0b69300), but it
has been present since hyper 0.6.0 and would be nice to include here.

feat(response): add Authorization<Bearer> as a `set`table type

---

Cargo.toml
src/router/into_matcher.rs
src/router/router.rs

regex          0.1 -> 0.2
mustache       0.6 -> 0.8
hyper          0.9 -> 0.10
lazy_static    0.1 -> 0.2
compiletest_rs 0.1 -> 0.2
Note: since hyper removed ssl support, nickel no longer has it

chore(*): Upgrade Crates, Increase version to 0.10

---

.travis.yml
examples/form_data/form_data.rs
examples/hello_world.rs
examples/integration_testing.rs
examples/macro_example.rs
examples/no_macro_custom_data.rs
examples/static_files.rs
examples/template.rs
src/body_parser.rs
src/extensions/request.rs
src/extensions/response.rs
src/macros/middleware.rs
src/query_string.rs
src/response.rs
src/urlencoded.rs

Fix the examples that were returning MiddlewareResults in the
middlware! macro. A couple could be changed to return a Responder, but
most needed to be reimplemented as seperate functions.
Updated the middleware! macro documentaion to note the limitations
from issues #399 and #389.

fix(examples): Fix examples triggering issue #399

---

src/nickel.rs

Nickel::listen() and Nickel::listen_https() check for the presence
of $NICKEL_TEST_HARNESS in a way which causes a panic if any value
in the environment contains a non-UTF8 string. This patch fixes
the check.
Fixes #379

fix: don't panic with non-UTF8 environment

---

src/lib.rs
src/nickel.rs
src/response.rs
src/server.rs
src/template_cache.rs

Change TemplateCache to be a struct to add support for a variety of
ways to refresh compiled mustache templates.
* Templates can be explicitly reloaded with the TemplateCache::clear
and TemplateCache::reload_template methods.
* ReloadPolicy can control automatic reloading when templates are
rendered. The default of ReloadPolicy::Never is the previous
behavior.
To support this, two new Nickel contructor methods were added to take
a nickel::Options struct.

feat(templates): Support reloading templates

---

contributing.md

This adds a space before headers in [contributing.md](https://github.com/nickel-org/nickel.rs/blob/master/contributing.md). Currently the headers don't have a space so they look like this:
##HeaderExample
The header should have a space in between the "##" and the text like this:

fix contributing.md formatting

---

examples/enable_cors_header_set_issue.rs

I've added the `options` endpoint in order to enable preflight requests and also created a new example using manual setting of the headers to avoid issue mentioned in #365 & #324.

Working cors examples

---

examples/json.rs

This fixes the example curl command routes in examples/json.rs
File also was reformatted by rustfmt

Fixed curl routes in examples/json.rs

---

src/urlencoded.rs

Add a method `map() -> &HashMap<String, Vec<String>>` to `nickel::Params` that exposes the full query map.
Fixes #376.

Expose query params as a map

---

Cargo.toml
examples/no_macro_response_custom_data.rs

This commit shows how to use a struct that can be set at some point in the middleware stack and reuse later on in another layer.

example(MW): shows how to share information in the middleware stack

---

Cargo.toml

I was unable to create an example on the latest version of Rust.
Now everything works fine (tests and examples) and is up to date.

chore(*): update dependencies and Rust edition
